branches: [main]
repositoryUrl: "https://github.com/robproject/fsjd.git"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
