name: Diff Sample
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.ref }}

      - name: Setup requirements
        run: |
          pip install rich
          pip install json_source_map
          # wget https://raw.githubusercontent.com/robproject/fsjd/main/frappe_schema_json_diff.py
          echo "GIT_EXTERNAL_DIFF=./frappe_schema_json_diff.py" >> $GITHUB_ENV
          echo "TABLE_MODE=1" >> $GITHUB_ENV
      
      - name: Diff
        run: |
          git --no-pager diff HEAD~1 HEAD




