name: Diff Sample
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 2

      - name: Setup requirements and script
        run: |
          pip install rich
          pip install json_source_map
          wget https://raw.githubusercontent.com/robproject/fsjd/main/frappe_schema_json_diff.py

      - name: Run script file
        run: |
          chmod +x ./run.sh
          ./run.sh
        shell: bash


