name: Validate Diff Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 2

      - name: find changed json
        id: changed-json
        uses: tj-actions/changed-files@v23.1
        with:
          files: |
            **/*.json
          include_all_old_new_renamed_files: true

      - name: cp head paths files
        run: |
          mkdir head
          touch head/acmr.txt
          for file in ${{ steps.changed-json.outputs.added_files }}; do
            echo "A,head/${file}" >> head/acmr.txt
            cp --parents $file head/
          done
          for file in ${{ steps.changed-json.outputs.copied_files }}; do
            echo "C,head/${file}" >> head/acmr.txt
            cp --parents $file head/
          done
          for file in ${{ steps.changed-json.outputs.modified_files }}; do
            echo "M,head/${file}" >> head/acmr.txt
            cp --parents $file head/
          done
          for file in ${{ steps.changed-json.outputs.renamed_files }}; do
            echo "R,head/${file}" >> head/acmr.txt
            cp --parents $file head/
          done

      - name: checkout base
        run: git checkout $(git --no-pager log --oneline -n 2 | awk 'NR==2 {print $1}')

      - name: cp base paths
        run: |
          mkdir base
          touch base/mrd.txt
          for file in ${{ steps.changed-json.outputs.modified_files }}; do
            echo "M,${file}" >> base/mrd.txt
          done
          for file in ${{ steps.changed-json.outputs.all_old_new_renamed_files }}; do
            echo "R,${file}" >> base/mrd.txt
          done
          for file in ${{ steps.changed-json.outputs.deleted_files }}; do
            echo "D,${file}" >> base/mrd.txt
          done

      - name: Diff JSON
        run: |
          pip install rich
          pip install json_source_map
          git clone https://gist.github.com/74017707b676c3ce947528fb00dd46d0.git frappe_json_diff
          python3 frappe_json_diff/frappe_json_diff.py base/mrd.txt head/acmr.txt 1

