name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: steps.semantic-release.outputs.released == 'true'   # only run if new version
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
