name: Release
on:
  push:
    branches:
      - main

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: Robert Duncan
          git_committer_email: robirtduncan@gmail.com
